In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [ ]:
# 학습 데이터 셋
x_train = torch.FloatTensor([[1], [2], [3], [4]])
y_train = torch.FloatTensor([[50], [70], [90], [85]])

In [ ]:
# y = W(weight)x + b(bias)

'''
y = 20x + 15     <- 임의의 기울기

시간     1   2   3   4
실제값  50  70  90  85
예측값  35  55  75  95
----------------------
오차값  15  15  15  -10
'''

# MSE(평균 제곱 오차)
# 오차를 제곱하고 평균으로 나눈 것

# 코드를 재실행해도 같은 랜덤 결과가 나옴
torch.manual_seed(10) # 숫자는 아무거나 주어도 상관 없음

print(x_train)
print(x_train.shape)

print(y_train)
print(y_train.shape)

# 선형회귀의 핵심은 학습데이터와 가장 잘 맞는 직선을 찾는 작업
# requires_grad=True : 학습을 통해 변경되는 변수(값이 업데이트 가능하도록 변수로 설정)
W = torch.zeros(1, requires_grad=True)
print(W)

b = torch.zeros(1, requires_grad=True)
print(b)

H = x_train * W + b

tensor([[1.],
        [2.],
        [3.],
        [4.]])
torch.Size([4, 1])
tensor([[50.],
        [70.],
        [90.],
        [85.]])
torch.Size([4, 1])
tensor([0.], requires_grad=True)
tensor([0.], requires_grad=True)


In [ ]:
# 비용 함수 선언(Cost Function, 손실함수(Loss Function), 오차 함수(Error Function))
cost = torch.mean((H - y_train) ** 2)
print(cost)

tensor(5681.2500, grad_fn=<MeanBackward0>)


In [ ]:
# optimizer
# 비용 함수의 값을 최소화 하는 W(기울기)와 b(절편)을 찾는 방법(알고리즘)

# 경사 하강법(Gradient Descent)
# 가장 기본적인 최적화 알고리즘
# cost가 최소화 되는 지점은 접선의 기울기가 0이 되는 지점이며, 미분값이 0이 되는 지점
# 비용함수를 미분하여 현재 W에서의 접선의 기울기를 구하고 접선의 기울기가 낮은 방향으로 W의 값을 업데이트 하는 작업을 반복

# SGD(Stochastic Gradient Descent)
# 배치 크기가 1인 경사하강법 알고리즘. 
# 확률적 경사 하강법은 데이터 셋에서 무작위로 균일하게 선택한 하나의 샘플을 의존하여 각 단계의 예측 경사를 계산

# 학습률(learning rate)
# 기울기의 값을 변경할 때 얼마나 크게 변경할지를 결정
optimizer= optim.SGD([W, b], lr=0.01)

In [ ]:
# 에폭을 한번 돌 때마다 gradient를 0으로 초기화 해줘야 함
optimizer.zero_grad()
# 비용함수를 미분하여 gradient 계산
cost.backward() # 역전파
# W와 b를 업데이트
optimizer.step()

In [ ]:
# 에폭(epoch) : 전체 훈련 데이터가 학습에 한번 사용된 주기
# 총 에폭을 2000번. 100번마다 로그 출력

x_train = torch.FloatTensor([[1], [2], [3], [4]]) # 시간
y_train = torch.FloatTensor([[50], [70], [90], [85]]) # 점수

W = torch.zeros(1, requires_grad=True) # 변수 취급. 0으로 세팅
b = torch.zeros(1, requires_grad=True) # 변수 취급. 0으로 세팅

optimizer = optim.SGD([W, b], lr=0.01) # SGD 최적화 사용.

for epoch in range(1, 2001): # 2000바퀴

    H = x_train * W + b
    cost = torch.mean((H - y_train) ** 2) # 오차값

    optimizer.zero_grad() # 초기화
    cost.backward() # 역전파
    optimizer.step() # W, b 값을 업데이트

    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W:{:.3f} b:{:.3f} Cost:{:.6f}'.format(epoch, 2000, W.item(), b.item(), cost.item()))

Epoch  100/2000 W:21.140 b:17.099 Cost:155.283264
Epoch  200/2000 W:18.901 b:23.679 Cost:106.389832
Epoch  300/2000 W:17.243 b:28.555 Cost:79.547897
Epoch  400/2000 W:16.014 b:32.168 Cost:64.812042
Epoch  500/2000 W:15.104 b:34.844 Cost:56.722210
Epoch  600/2000 W:14.429 b:36.828 Cost:52.280975
Epoch  700/2000 W:13.929 b:38.297 Cost:49.842865
Epoch  800/2000 W:13.559 b:39.386 Cost:48.504280
Epoch  900/2000 W:13.285 b:40.193 Cost:47.769455
Epoch 1000/2000 W:13.081 b:40.790 Cost:47.366051
Epoch 1100/2000 W:12.931 b:41.233 Cost:47.144569
Epoch 1200/2000 W:12.819 b:41.561 Cost:47.023003
Epoch 1300/2000 W:12.737 b:41.805 Cost:46.956245
Epoch 1400/2000 W:12.675 b:41.985 Cost:46.919601
Epoch 1500/2000 W:12.630 b:42.118 Cost:46.899479
Epoch 1600/2000 W:12.596 b:42.217 Cost:46.888451
Epoch 1700/2000 W:12.571 b:42.290 Cost:46.882359
Epoch 1800/2000 W:12.553 b:42.345 Cost:46.879055
Epoch 1900/2000 W:12.539 b:42.385 Cost:46.877216
Epoch 2000/2000 W:12.529 b:42.415 Cost:46.876221


In [ ]:
model = nn.Linear(1, 1) # 입력 데이터 수, 출력 데이터 수 -> 데이터 1개 넣어서 1개 결과 출력할 거다

In [ ]:
class LinearRegressionModel(nn.Module): # nn.Module을 상속받음
  def __init__(self):
    super().__init__() # nn.Module의 부모 클래스를 불러옴
    self.linear = nn.Linear(1, 1) # __setattr__ 함수를 실행
  
  def forward(self, x): # forward()함수는 nn,Module 내부에 있는 함수여서 여기서 오버라이딩 해주는 것
    return self.linear(x) # x값 계산해서 결과값 리턴


In [ ]:
x_train = torch.FloatTensor([[1], [2], [3], [4]])
y_train = torch.FloatTensor([[50], [70], [90], [85]])

In [ ]:
model = LinearRegressionModel()

In [ ]:
# optimizer는 model.parameter()를 통해 W와 b를 가져오고 러닝 레이트를 참고해서 가중치를 업데이트 하기 위한 객체
# model.parameters() : 입력 받고 레이어를 넘길 때의 가중치를 뽑아내는 메소드.
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
for epoch in range(1, 2001):
  H = model(x_train)
  cost = F.mse_loss(H, y_train)

  optimizer.zero_grad() # 초기화
  cost.backward() # 역전파
  optimizer.step() # W, b 값을 업데이트

  if epoch % 100 == 0:
        print('Epoch {:4d}/{} W:{:.3f} b:{:.3f} Cost:{:.6f}'.format(epoch, 2000, W.item(), b.item(), cost.item()))

Epoch  100/2000 W:12.529 b:42.415 Cost:153.265686
Epoch  200/2000 W:12.529 b:42.415 Cost:105.282211
Epoch  300/2000 W:12.529 b:42.415 Cost:78.939957
Epoch  400/2000 W:12.529 b:42.415 Cost:64.478210
Epoch  500/2000 W:12.529 b:42.415 Cost:56.538986
Epoch  600/2000 W:12.529 b:42.415 Cost:52.180420
Epoch  700/2000 W:12.529 b:42.415 Cost:49.787621
Epoch  800/2000 W:12.529 b:42.415 Cost:48.473969
Epoch  900/2000 W:12.529 b:42.415 Cost:47.752815
Epoch 1000/2000 W:12.529 b:42.415 Cost:47.356934
Epoch 1100/2000 W:12.529 b:42.415 Cost:47.139538
Epoch 1200/2000 W:12.529 b:42.415 Cost:47.020203
Epoch 1300/2000 W:12.529 b:42.415 Cost:46.954765
Epoch 1400/2000 W:12.529 b:42.415 Cost:46.918800
Epoch 1500/2000 W:12.529 b:42.415 Cost:46.899036
Epoch 1600/2000 W:12.529 b:42.415 Cost:46.888199
Epoch 1700/2000 W:12.529 b:42.415 Cost:46.882233
Epoch 1800/2000 W:12.529 b:42.415 Cost:46.878956
Epoch 1900/2000 W:12.529 b:42.415 Cost:46.877151
Epoch 2000/2000 W:12.529 b:42.415 Cost:46.876186


In [ ]:
val = torch.FloatTensor([[5.0]])
pred = model(val)
print('학습 후 5시간 공부하면 예상되는 성적: ', pred)

학습 후 5시간 공부하면 예상되는 성적:  tensor([[105.0592]], grad_fn=<AddmmBackward0>)


In [ ]:
print(list(model.parameters()))

[Parameter containing:
tensor([[12.5287]], requires_grad=True), Parameter containing:
tensor([42.4155], requires_grad=True)]
